# version: "3.9"

services:
  altheia_chat_backend:
    container_name: altheia_chat_backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8011:8080"
    restart: unless-stopped

  altheia_chat_frontend:
    container_name: altheia_chat_frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "8505:8501"
    depends_on:
      - altheia_chat_backend
    restart: unless-stopped

  redis:
    image: redis:7.4
    container_name: altheia_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
   # profiles: ['sql-stack']

volumes:
  redis_data:
    name: redis_data

networks:
  default:
    name: altheia_network
